# This is a basic workflow to help you get started with Actions

name: Deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    name: "deploy"
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    timeout-minutes: 30

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: npm install
      - name: Add secrets
        uses: jsdaniell/create-json@1.1.2
        with:
          # The name of the file to be written. | file.json
          name: keys.json
          json: ${{ secrets.LASTFM_CREDENTIALS }}
          dir: themes/ta-portfolio/src/js
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
      - name: Build
        run: npm run build
      - name: List output files
        run: ls public
      - name: Deploy to server
        # uses: milanmk/actions-file-deployer@1.9
        # with:
        #   remote-user: '${{ secrets.SERVER_USERNAME }}'
        #   remote-host: '${{ secrets.SERVER_HOST }}'
        #   remote-password: ${{ secrets.SERVER_PASSWORD }}
        #   local-path: './public'
        #   remote-path: '/www'
        #   sync: "full"
        #uses: sand4rt/ftp-deployer@v1.3
        #with:
          #sftp: true # optional
          #host: ${{ secrets.SERVER_HOST }} # e.g. ftp.host.com or sftp.host.com (without ftp:// or ftps://)
          #port: 22 # optional, default is: 21
          #username: ${{ secrets.SERVER_USERNAME }} # FTP username
          #password: ${{ secrets.SERVER_PASSWORD }} # FTP password
          #remote_folder: ${{ secrets.SERVER_TARGET }} # optional, remote path of your FTP server
          #local_folder: public # optional, local path, default is: dist
          #cleanup: false # optional, remove existing files inside FTP remote folder
          # include: [] # optional, e.g. ['dist']
          # exclude: [] # optional, e.g. ['node_modules/**', '.git/**', '*.env']
          # pasive: true # optional
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.SERVER_USERNAME }}
          server: ${{ secrets.SERVER_HOST }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          local_path: 'public/'
          remote_path: ${{ secrets.SERVER_TARGET }}
          sftpArgs: '-o ConnectTimeout=5'
